spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

com.foo.topic: test-topic