server:
  port: 9090
spring:
    kafka:
      topic: hello-topic
      bootstrap-servers: localhost:9092
      producer:
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
